// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';

export function DeleteAgent(arg1:string):Promise<void>;

export function ListAgents():Promise<Array<storage.Agent>>;

export function SaveAgent(arg1:storage.Agent):Promise<storage.Agent>;
