// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAgent(arg1) {
  return window['go']['handler']['AgentHandler']['DeleteAgent'](arg1);
}

export function ListAgents() {
  return window['go']['handler']['AgentHandler']['ListAgents']();
}

export function SaveAgent(arg1) {
  return window['go']['handler']['AgentHandler']['SaveAgent'](arg1);
}
