// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handler} from '../models';

export function Backup():Promise<void>;

export function GetConfig():Promise<handler.WebDAVConfig>;

export function ListBackups():Promise<Array<string>>;

export function Restore(arg1:string):Promise<void>;

export function SaveConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
