// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Backup() {
  return window['go']['handler']['BackupHandler']['Backup']();
}

export function DeleteBackup(arg1) {
  return window['go']['handler']['BackupHandler']['DeleteBackup'](arg1);
}

export function GetConfig() {
  return window['go']['handler']['BackupHandler']['GetConfig']();
}

export function ListBackups() {
  return window['go']['handler']['BackupHandler']['ListBackups']();
}

export function Restore(arg1) {
  return window['go']['handler']['BackupHandler']['Restore'](arg1);
}

export function SaveConfig(arg1, arg2, arg3, arg4) {
  return window['go']['handler']['BackupHandler']['SaveConfig'](arg1, arg2, arg3, arg4);
}
