// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {handler} from '../models';

export function SendMessage(arg1:context.Context,arg2:handler.SendMessageRequest):Promise<handler.SendMessageResponse>;

export function StreamChat(arg1:context.Context,arg2:handler.SendMessageRequest):Promise<void>;
