// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {handler} from '../models';

export function CancelStream():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StreamChat(arg1:handler.SendMessageRequest):Promise<void>;
