// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SendMessage(arg1, arg2) {
  return window['go']['handler']['ChatHandler']['SendMessage'](arg1, arg2);
}

export function StreamChat(arg1, arg2) {
  return window['go']['handler']['ChatHandler']['StreamChat'](arg1, arg2);
}
