// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelStream() {
  return window['go']['handler']['ChatHandler']['CancelStream']();
}

export function SetContext(arg1) {
  return window['go']['handler']['ChatHandler']['SetContext'](arg1);
}

export function StreamChat(arg1) {
  return window['go']['handler']['ChatHandler']['StreamChat'](arg1);
}
