// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';

export function Create(arg1:string,arg2:string):Promise<storage.Conversation>;

export function Delete(arg1:string):Promise<void>;

export function Get(arg1:string):Promise<storage.Conversation>;

export function GetMessages(arg1:string):Promise<Array<storage.Message>>;

export function List():Promise<Array<storage.Conversation>>;

export function Rename(arg1:string,arg2:string):Promise<void>;
