// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2) {
  return window['go']['handler']['ConversationHandler']['Create'](arg1, arg2);
}

export function Delete(arg1) {
  return window['go']['handler']['ConversationHandler']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['handler']['ConversationHandler']['Get'](arg1);
}

export function GetMessages(arg1) {
  return window['go']['handler']['ConversationHandler']['GetMessages'](arg1);
}

export function List() {
  return window['go']['handler']['ConversationHandler']['List']();
}

export function ListFavorites() {
  return window['go']['handler']['ConversationHandler']['ListFavorites']();
}

export function Rename(arg1, arg2) {
  return window['go']['handler']['ConversationHandler']['Rename'](arg1, arg2);
}

export function Search(arg1) {
  return window['go']['handler']['ConversationHandler']['Search'](arg1);
}

export function SetAgent(arg1, arg2) {
  return window['go']['handler']['ConversationHandler']['SetAgent'](arg1, arg2);
}

export function SetModel(arg1, arg2, arg3) {
  return window['go']['handler']['ConversationHandler']['SetModel'](arg1, arg2, arg3);
}

export function SetSystemPrompt(arg1, arg2) {
  return window['go']['handler']['ConversationHandler']['SetSystemPrompt'](arg1, arg2);
}

export function ToggleFavorite(arg1) {
  return window['go']['handler']['ConversationHandler']['ToggleFavorite'](arg1);
}
