// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateKnowledgeBase(arg1, arg2) {
  return window['go']['handler']['KnowledgeHandler']['CreateKnowledgeBase'](arg1, arg2);
}

export function DeleteDocument(arg1, arg2) {
  return window['go']['handler']['KnowledgeHandler']['DeleteDocument'](arg1, arg2);
}

export function DeleteKnowledgeBase(arg1) {
  return window['go']['handler']['KnowledgeHandler']['DeleteKnowledgeBase'](arg1);
}

export function GetDocumentStatus(arg1, arg2) {
  return window['go']['handler']['KnowledgeHandler']['GetDocumentStatus'](arg1, arg2);
}

export function ListDocuments(arg1) {
  return window['go']['handler']['KnowledgeHandler']['ListDocuments'](arg1);
}

export function ListKnowledgeBases() {
  return window['go']['handler']['KnowledgeHandler']['ListKnowledgeBases']();
}

export function PickAndUploadDocuments(arg1) {
  return window['go']['handler']['KnowledgeHandler']['PickAndUploadDocuments'](arg1);
}

export function SetContext(arg1) {
  return window['go']['handler']['KnowledgeHandler']['SetContext'](arg1);
}
