// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {kb} from '../models';
import {context} from '../models';

export function CreateKnowledgeBase(arg1:string,arg2:string):Promise<storage.KnowledgeBase>;

export function DeleteDocument(arg1:string,arg2:string):Promise<void>;

export function DeleteKnowledgeBase(arg1:string):Promise<void>;

export function GetDocumentStatus(arg1:string,arg2:string):Promise<string>;

export function ListDocuments(arg1:string):Promise<Array<kb.KBDocument>>;

export function ListKnowledgeBases():Promise<Array<storage.KnowledgeBase>>;

export function PickAndUploadDocuments(arg1:string):Promise<Array<kb.KBDocument>>;

export function RebuildIndex(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
