// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['handler']['MCPHandler']['Delete'](arg1);
}

export function List() {
  return window['go']['handler']['MCPHandler']['List']();
}

export function Save(arg1) {
  return window['go']['handler']['MCPHandler']['Save'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['handler']['MCPHandler']['TestConnection'](arg1);
}

export function Toggle(arg1, arg2) {
  return window['go']['handler']['MCPHandler']['Toggle'](arg1, arg2);
}
