// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';

export function Delete(arg1:string):Promise<void>;

export function List():Promise<Array<storage.MCPServer>>;

export function Save(arg1:storage.MCPServer):Promise<void>;

export function TestConnection(arg1:storage.MCPServer):Promise<Array<string>>;

export function Toggle(arg1:string,arg2:boolean):Promise<void>;
