// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';

export function AddModel(arg1:storage.LLMModel):Promise<void>;

export function DeleteModel(arg1:string):Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function ListEnabledModels():Promise<Array<storage.LLMModel>>;

export function ListModels(arg1:string):Promise<Array<storage.LLMModel>>;

export function ListProviders():Promise<Array<storage.LLMProvider>>;

export function SaveProvider(arg1:storage.LLMProvider):Promise<storage.LLMProvider>;

export function ToggleProvider(arg1:string,arg2:boolean):Promise<void>;
