// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddModel(arg1) {
  return window['go']['handler']['ProviderHandler']['AddModel'](arg1);
}

export function DeleteModel(arg1) {
  return window['go']['handler']['ProviderHandler']['DeleteModel'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['handler']['ProviderHandler']['DeleteProvider'](arg1);
}

export function ListEnabledModels() {
  return window['go']['handler']['ProviderHandler']['ListEnabledModels']();
}

export function ListModels(arg1) {
  return window['go']['handler']['ProviderHandler']['ListModels'](arg1);
}

export function ListProviders() {
  return window['go']['handler']['ProviderHandler']['ListProviders']();
}

export function SaveProvider(arg1) {
  return window['go']['handler']['ProviderHandler']['SaveProvider'](arg1);
}

export function ToggleProvider(arg1, arg2) {
  return window['go']['handler']['ProviderHandler']['ToggleProvider'](arg1, arg2);
}
