// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';

export function Get(arg1:string):Promise<string>;

export function GetAll():Promise<Array<storage.Setting>>;

export function Set(arg1:string,arg2:string):Promise<void>;
