// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';

export function DeleteSkill(arg1:string):Promise<void>;

export function ImportSkillZip(arg1:Array<number>,arg2:string):Promise<Array<storage.Skill>>;

export function ListSkills():Promise<Array<storage.Skill>>;

export function SaveSkill(arg1:storage.Skill):Promise<storage.Skill>;

export function ToggleSkill(arg1:string,arg2:boolean):Promise<void>;
