// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSkill(arg1) {
  return window['go']['handler']['SkillHandler']['DeleteSkill'](arg1);
}

export function ImportSkillZip(arg1, arg2) {
  return window['go']['handler']['SkillHandler']['ImportSkillZip'](arg1, arg2);
}

export function ListSkills() {
  return window['go']['handler']['SkillHandler']['ListSkills']();
}

export function SaveSkill(arg1) {
  return window['go']['handler']['SkillHandler']['SaveSkill'](arg1);
}

export function ToggleSkill(arg1, arg2) {
  return window['go']['handler']['SkillHandler']['ToggleSkill'](arg1, arg2);
}
