// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmBash(arg1, arg2, arg3) {
  return window['go']['handler']['TaskHandler']['ConfirmBash'](arg1, arg2, arg3);
}

export function OpenPath(arg1, arg2) {
  return window['go']['handler']['TaskHandler']['OpenPath'](arg1, arg2);
}

export function SelectWorkDir() {
  return window['go']['handler']['TaskHandler']['SelectWorkDir']();
}

export function SetContext(arg1) {
  return window['go']['handler']['TaskHandler']['SetContext'](arg1);
}

export function StopTask(arg1) {
  return window['go']['handler']['TaskHandler']['StopTask'](arg1);
}

export function StreamTask(arg1) {
  return window['go']['handler']['TaskHandler']['StreamTask'](arg1);
}
